name = "MCTBetaScaling"
uuid = "89e7ec30-1fdf-11ee-08a6-c5e7866bad12"
authors = ["s158686 "]
version = "0.0.1"

[deps]
ModeCouplingTheory = "6cad4188-63cb-4528-a10f-dbb409b456c6"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ModeCouplingTheory = "0.7, 0.8"
SpecialFunctions = "2"
